-- MySQL Script generated by MySQL Workbench
-- 04/10/16 00:16:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hmts_repos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hmts_repos` ;

-- -----------------------------------------------------
-- Schema hmts_repos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hmts_repos` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `hmts_repos` ;

-- -----------------------------------------------------
-- Table `hmts_repos`.`secquestion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmts_repos`.`secquestion` ;

CREATE TABLE IF NOT EXISTS `hmts_repos`.`secquestion` (
  `sec_question_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `content` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`sec_question_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmts_repos`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmts_repos`.`user` ;

CREATE TABLE IF NOT EXISTS `hmts_repos`.`user` (
  `user_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(45) NOT NULL COMMENT '',
  `first_name` VARCHAR(45) NOT NULL COMMENT '',
  `last_name` VARCHAR(45) NULL COMMENT '',
  `phone` VARCHAR(45) NULL COMMENT '',
  `role` VARCHAR(45) NOT NULL COMMENT '',
  `sec_question_id` INT NULL COMMENT '',
  `sec_answer` VARCHAR(45) NULL COMMENT '',
  `tag` VARCHAR(100) NULL DEFAULT 'N/A' COMMENT '',
  PRIMARY KEY (`user_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmts_repos`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmts_repos`.`product` ;

CREATE TABLE IF NOT EXISTS `hmts_repos`.`product` (
  `product_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `type` VARCHAR(45) NOT NULL COMMENT '',
  `price` DOUBLE NOT NULL COMMENT '',
  `brief` VARCHAR(500) NULL DEFAULT 'N/A' COMMENT '',
  PRIMARY KEY (`product_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmts_repos`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmts_repos`.`order` ;

CREATE TABLE IF NOT EXISTS `hmts_repos`.`order` (
  `order_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `ship_address` VARCHAR(100) NOT NULL COMMENT '',
  `phone` VARCHAR(45) NOT NULL COMMENT '',
  `note` VARCHAR(500) NULL DEFAULT 'N/A' COMMENT '',
  `status` VARCHAR(45) NOT NULL COMMENT '',
  `user_id` BIGINT NOT NULL COMMENT '',
  PRIMARY KEY (`order_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmts_repos`.`selproduct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmts_repos`.`selproduct` ;

CREATE TABLE IF NOT EXISTS `hmts_repos`.`selproduct` (
  `product_id` BIGINT NOT NULL COMMENT '',
  `user_id` BIGINT NOT NULL COMMENT '',
  `quantity` INT NOT NULL COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmts_repos`.`function`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmts_repos`.`function` ;

CREATE TABLE IF NOT EXISTS `hmts_repos`.`function` (
  `function_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `description` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`function_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmts_repos`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmts_repos`.`payment` ;

CREATE TABLE IF NOT EXISTS `hmts_repos`.`payment` (
  `payment_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `method` VARCHAR(45) NOT NULL COMMENT '',
  `amount` DOUBLE NOT NULL COMMENT '',
  `order_id` BIGINT NOT NULL COMMENT '',
  PRIMARY KEY (`payment_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmts_repos`.`card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmts_repos`.`card` ;

CREATE TABLE IF NOT EXISTS `hmts_repos`.`card` (
  `card_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `card_num` VARCHAR(45) NOT NULL COMMENT '',
  `card_owner` VARCHAR(45) NOT NULL COMMENT '',
  `bill_address` VARCHAR(100) NOT NULL COMMENT '',
  `exp_date` DATE NOT NULL COMMENT '',
  `sec_code` VARCHAR(45) NOT NULL COMMENT '',
  `bs_consistency` INT NOT NULL COMMENT '',
  `payment_id` BIGINT NOT NULL COMMENT '',
  PRIMARY KEY (`card_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmts_repos`.`orderproduct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmts_repos`.`orderproduct` ;

CREATE TABLE IF NOT EXISTS `hmts_repos`.`orderproduct` (
  `orderproduct_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `product_id` BIGINT NOT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `type` VARCHAR(45) NOT NULL COMMENT '',
  `price` DOUBLE NOT NULL COMMENT '',
  `brief` VARCHAR(100) NOT NULL COMMENT '',
  `order_id` BIGINT NOT NULL COMMENT '',
  `quantity` INT NOT NULL COMMENT '',
  `amount` DOUBLE NOT NULL COMMENT '',
  PRIMARY KEY (`orderproduct_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmts_repos`.`functionrole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmts_repos`.`functionrole` ;

CREATE TABLE IF NOT EXISTS `hmts_repos`.`functionrole` (
  `function_id` INT NOT NULL COMMENT '',
  `role` VARCHAR(45) NOT NULL COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
