package edu.fiu.hmts.domain.hmts_repos;

import java.util.Date;

/**
 * The Class Card.
 */
public class Card {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.card_id
     *
     * @mbggenerated Sun Apr 10 22:11:08 EDT 2016
     */
    private Long cardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.card_num
     *
     * @mbggenerated Sun Apr 10 22:11:08 EDT 2016
     */
    private String cardNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.card_owner
     *
     * @mbggenerated Sun Apr 10 22:11:08 EDT 2016
     */
    private String cardOwner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.bill_address
     *
     * @mbggenerated Sun Apr 10 22:11:08 EDT 2016
     */
    private String billAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.exp_date
     *
     * @mbggenerated Sun Apr 10 22:11:08 EDT 2016
     */
    private Date expDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.sec_code
     *
     * @mbggenerated Sun Apr 10 22:11:08 EDT 2016
     */
    private String secCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.bs_consistency
     *
     * @mbggenerated Sun Apr 10 22:11:08 EDT 2016
     */
    private Integer bsConsistency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.payment_id
     *
     * @mbggenerated Sun Apr 10 22:11:08 EDT 2016
     */
    private Long paymentId;

    /**
	 * Gets the card id.
	 *
	 * @return the card id
	 */
    public Long getCardId() {
        return cardId;
    }

    /**
	 * Sets the card id.
	 *
	 * @param cardId
	 *            the new card id
	 */
    public void setCardId(Long cardId) {
        this.cardId = cardId;
    }

    /**
	 * Gets the card num.
	 *
	 * @return the card num
	 */
    public String getCardNum() {
        return cardNum;
    }

    /**
	 * Sets the card num.
	 *
	 * @param cardNum
	 *            the new card num
	 */
    public void setCardNum(String cardNum) {
        this.cardNum = cardNum == null ? null : cardNum.trim();
    }

    /**
	 * Gets the card owner.
	 *
	 * @return the card owner
	 */
    public String getCardOwner() {
        return cardOwner;
    }

    /**
	 * Sets the card owner.
	 *
	 * @param cardOwner
	 *            the new card owner
	 */
    public void setCardOwner(String cardOwner) {
        this.cardOwner = cardOwner == null ? null : cardOwner.trim();
    }

    /**
	 * Gets the bill address.
	 *
	 * @return the bill address
	 */
    public String getBillAddress() {
        return billAddress;
    }

    /**
	 * Sets the bill address.
	 *
	 * @param billAddress
	 *            the new bill address
	 */
    public void setBillAddress(String billAddress) {
        this.billAddress = billAddress == null ? null : billAddress.trim();
    }

    /**
	 * Gets the exp date.
	 *
	 * @return the exp date
	 */
    public Date getExpDate() {
        return expDate;
    }

    /**
	 * Sets the exp date.
	 *
	 * @param expDate
	 *            the new exp date
	 */
    public void setExpDate(Date expDate) {
        this.expDate = expDate;
    }

    /**
	 * Gets the sec code.
	 *
	 * @return the sec code
	 */
    public String getSecCode() {
        return secCode;
    }

    /**
	 * Sets the sec code.
	 *
	 * @param secCode
	 *            the new sec code
	 */
    public void setSecCode(String secCode) {
        this.secCode = secCode == null ? null : secCode.trim();
    }

    /**
	 * Gets the bs consistency.
	 *
	 * @return the bs consistency
	 */
    public Integer getBsConsistency() {
        return bsConsistency;
    }

    /**
	 * Sets the bs consistency.
	 *
	 * @param bsConsistency
	 *            the new bs consistency
	 */
    public void setBsConsistency(Integer bsConsistency) {
        this.bsConsistency = bsConsistency;
    }

    /**
	 * Gets the payment id.
	 *
	 * @return the payment id
	 */
    public Long getPaymentId() {
        return paymentId;
    }

    /**
	 * Sets the payment id.
	 *
	 * @param paymentId
	 *            the new payment id
	 */
    public void setPaymentId(Long paymentId) {
        this.paymentId = paymentId;
    }
}