package edu.fiu.hmts.dao.mybatis.dao;

import edu.fiu.hmts.domain.Function;
import edu.fiu.hmts.domain.FunctionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table function
     *
     * @mbggenerated Sun Feb 28 23:35:35 EST 2016
     */
    int countByExample(FunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table function
     *
     * @mbggenerated Sun Feb 28 23:35:35 EST 2016
     */
    int deleteByExample(FunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table function
     *
     * @mbggenerated Sun Feb 28 23:35:35 EST 2016
     */
    int deleteByPrimaryKey(Integer functionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table function
     *
     * @mbggenerated Sun Feb 28 23:35:35 EST 2016
     */
    int insert(Function record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table function
     *
     * @mbggenerated Sun Feb 28 23:35:35 EST 2016
     */
    int insertSelective(Function record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table function
     *
     * @mbggenerated Sun Feb 28 23:35:35 EST 2016
     */
    List<Function> selectByExample(FunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table function
     *
     * @mbggenerated Sun Feb 28 23:35:35 EST 2016
     */
    Function selectByPrimaryKey(Integer functionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table function
     *
     * @mbggenerated Sun Feb 28 23:35:35 EST 2016
     */
    int updateByExampleSelective(@Param("record") Function record, @Param("example") FunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table function
     *
     * @mbggenerated Sun Feb 28 23:35:35 EST 2016
     */
    int updateByExample(@Param("record") Function record, @Param("example") FunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table function
     *
     * @mbggenerated Sun Feb 28 23:35:35 EST 2016
     */
    int updateByPrimaryKeySelective(Function record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table function
     *
     * @mbggenerated Sun Feb 28 23:35:35 EST 2016
     */
    int updateByPrimaryKey(Function record);
}