package edu.fiu.hmts.domain;

/**
 * The Class CardKey.
 */
public class CardKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.card_id
     *
     * 
     */
    private Integer cardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.payment_id
     *
     * 
     */
    private Integer paymentId;

    /**
	 * Gets the card id.
	 *
	 * @return the card id
	 */
    public Integer getCardId() {
        return cardId;
    }

    /**
	 * Sets the card id.
	 *
	 * @param cardId
	 *            the new card id
	 */
    public void setCardId(Integer cardId) {
        this.cardId = cardId;
    }

    /**
	 * Gets the payment id.
	 *
	 * @return the payment id
	 */
    public Integer getPaymentId() {
        return paymentId;
    }

    /**
	 * Sets the payment id.
	 *
	 * @param paymentId
	 *            the new payment id
	 */
    public void setPaymentId(Integer paymentId) {
        this.paymentId = paymentId;
    }
}