package edu.fiu.hmts.domain;

public class FunctionRoleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column functionrole.function_id
     *
     * @mbggenerated Fri Apr 08 05:16:48 EDT 2016
     */
    private Integer functionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column functionrole.role
     *
     * @mbggenerated Fri Apr 08 05:16:48 EDT 2016
     */
    private String role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column functionrole.function_id
     *
     * @return the value of functionrole.function_id
     *
     * @mbggenerated Fri Apr 08 05:16:48 EDT 2016
     */
    public Integer getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column functionrole.function_id
     *
     * @param functionId the value for functionrole.function_id
     *
     * @mbggenerated Fri Apr 08 05:16:48 EDT 2016
     */
    public void setFunctionId(Integer functionId) {
        this.functionId = functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column functionrole.role
     *
     * @return the value of functionrole.role
     *
     * @mbggenerated Fri Apr 08 05:16:48 EDT 2016
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column functionrole.role
     *
     * @param role the value for functionrole.role
     *
     * @mbggenerated Fri Apr 08 05:16:48 EDT 2016
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }
}