package edu.fiu.hmts.domain;

/**
 * The Class OrderKey.
 */
public class OrderKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_id
     *
     * 
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.user_id
     *
     * 
     */
    private Integer userId;

    /**
	 * Gets the order id.
	 *
	 * @return the order id
	 */
    public Integer getOrderId() {
        return orderId;
    }

    /**
	 * Sets the order id.
	 *
	 * @param orderId
	 *            the new order id
	 */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
	 * Gets the user id.
	 *
	 * @return the user id
	 */
    public Integer getUserId() {
        return userId;
    }

    /**
	 * Sets the user id.
	 *
	 * @param userId
	 *            the new user id
	 */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}