package edu.fiu.hmts.domain;

/**
 * The Class OrderProductKey.
 */
public class OrderProductKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderproduct.orderproduct_id
     *
     * 
     */
    private Integer orderproductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderproduct.product_id
     *
     * 
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderproduct.order_id
     *
     * 
     */
    private Integer orderId;

    /**
	 * Gets the orderproduct id.
	 *
	 * @return the orderproduct id
	 */
    public Integer getOrderproductId() {
        return orderproductId;
    }

    /**
	 * Sets the orderproduct id.
	 *
	 * @param orderproductId
	 *            the new orderproduct id
	 */
    public void setOrderproductId(Integer orderproductId) {
        this.orderproductId = orderproductId;
    }

    /**
	 * Gets the product id.
	 *
	 * @return the product id
	 */
    public Integer getProductId() {
        return productId;
    }

    /**
	 * Sets the product id.
	 *
	 * @param productId
	 *            the new product id
	 */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
	 * Gets the order id.
	 *
	 * @return the order id
	 */
    public Integer getOrderId() {
        return orderId;
    }

    /**
	 * Sets the order id.
	 *
	 * @param orderId
	 *            the new order id
	 */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
}