package edu.fiu.hmts.domain;

public class OrderProductKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderproduct.orderproduct_id
     *
     * @mbggenerated Tue Apr 05 20:41:58 EDT 2016
     */
    private Integer orderproductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderproduct.product_id
     *
     * @mbggenerated Tue Apr 05 20:41:58 EDT 2016
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderproduct.order_id
     *
     * @mbggenerated Tue Apr 05 20:41:58 EDT 2016
     */
    private Integer orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderproduct.orderproduct_id
     *
     * @return the value of orderproduct.orderproduct_id
     *
     * @mbggenerated Tue Apr 05 20:41:58 EDT 2016
     */
    public Integer getOrderproductId() {
        return orderproductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderproduct.orderproduct_id
     *
     * @param orderproductId the value for orderproduct.orderproduct_id
     *
     * @mbggenerated Tue Apr 05 20:41:58 EDT 2016
     */
    public void setOrderproductId(Integer orderproductId) {
        this.orderproductId = orderproductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderproduct.product_id
     *
     * @return the value of orderproduct.product_id
     *
     * @mbggenerated Tue Apr 05 20:41:58 EDT 2016
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderproduct.product_id
     *
     * @param productId the value for orderproduct.product_id
     *
     * @mbggenerated Tue Apr 05 20:41:58 EDT 2016
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderproduct.order_id
     *
     * @return the value of orderproduct.order_id
     *
     * @mbggenerated Tue Apr 05 20:41:58 EDT 2016
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderproduct.order_id
     *
     * @param orderId the value for orderproduct.order_id
     *
     * @mbggenerated Tue Apr 05 20:41:58 EDT 2016
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
}