package edu.fiu.hmts.domain;

public class Payment extends PaymentKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.method
     *
     * @mbggenerated Sun Feb 28 23:35:35 EST 2016
     */
    private String method;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.amount
     *
     * @mbggenerated Sun Feb 28 23:35:35 EST 2016
     */
    private Double amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.method
     *
     * @return the value of payment.method
     *
     * @mbggenerated Sun Feb 28 23:35:35 EST 2016
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.method
     *
     * @param method the value for payment.method
     *
     * @mbggenerated Sun Feb 28 23:35:35 EST 2016
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.amount
     *
     * @return the value of payment.amount
     *
     * @mbggenerated Sun Feb 28 23:35:35 EST 2016
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.amount
     *
     * @param amount the value for payment.amount
     *
     * @mbggenerated Sun Feb 28 23:35:35 EST 2016
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }
}