package edu.fiu.hmts.domain;

/**
 * The Class PaymentKey.
 */
public class PaymentKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.payment_id
     *
     * 
     */
    private Integer paymentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.order_id
     *
     * 
     */
    private Integer orderId;

    /**
	 * Gets the payment id.
	 *
	 * @return the payment id
	 */
    public Integer getPaymentId() {
        return paymentId;
    }

    /**
	 * Sets the payment id.
	 *
	 * @param paymentId
	 *            the new payment id
	 */
    public void setPaymentId(Integer paymentId) {
        this.paymentId = paymentId;
    }

    /**
	 * Gets the order id.
	 *
	 * @return the order id
	 */
    public Integer getOrderId() {
        return orderId;
    }

    /**
	 * Sets the order id.
	 *
	 * @param orderId
	 *            the new order id
	 */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
}