package edu.fiu.hmts.domain;

public class Payment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.payment_id
     *
     * @mbggenerated Fri Apr 08 05:16:48 EDT 2016
     */
    private Long paymentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.method
     *
     * @mbggenerated Fri Apr 08 05:16:48 EDT 2016
     */
    private String method;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.amount
     *
     * @mbggenerated Fri Apr 08 05:16:48 EDT 2016
     */
    private Double amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.order_id
     *
     * @mbggenerated Fri Apr 08 05:16:48 EDT 2016
     */
    private Integer orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.payment_id
     *
     * @return the value of payment.payment_id
     *
     * @mbggenerated Fri Apr 08 05:16:48 EDT 2016
     */
    public Long getPaymentId() {
        return paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.payment_id
     *
     * @param paymentId the value for payment.payment_id
     *
     * @mbggenerated Fri Apr 08 05:16:48 EDT 2016
     */
    public void setPaymentId(Long paymentId) {
        this.paymentId = paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.method
     *
     * @return the value of payment.method
     *
     * @mbggenerated Fri Apr 08 05:16:48 EDT 2016
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.method
     *
     * @param method the value for payment.method
     *
     * @mbggenerated Fri Apr 08 05:16:48 EDT 2016
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.amount
     *
     * @return the value of payment.amount
     *
     * @mbggenerated Fri Apr 08 05:16:48 EDT 2016
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.amount
     *
     * @param amount the value for payment.amount
     *
     * @mbggenerated Fri Apr 08 05:16:48 EDT 2016
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.order_id
     *
     * @return the value of payment.order_id
     *
     * @mbggenerated Fri Apr 08 05:16:48 EDT 2016
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.order_id
     *
     * @param orderId the value for payment.order_id
     *
     * @mbggenerated Fri Apr 08 05:16:48 EDT 2016
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
}