package edu.fiu.hmts.domain;

import java.util.ArrayList;
import java.util.List;

public class SecQuestionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table secquestion
     *
     * @mbggenerated Sun Apr 10 20:24:21 EDT 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table secquestion
     *
     * @mbggenerated Sun Apr 10 20:24:21 EDT 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table secquestion
     *
     * @mbggenerated Sun Apr 10 20:24:21 EDT 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secquestion
     *
     * @mbggenerated Sun Apr 10 20:24:21 EDT 2016
     */
    public SecQuestionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secquestion
     *
     * @mbggenerated Sun Apr 10 20:24:21 EDT 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secquestion
     *
     * @mbggenerated Sun Apr 10 20:24:21 EDT 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secquestion
     *
     * @mbggenerated Sun Apr 10 20:24:21 EDT 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secquestion
     *
     * @mbggenerated Sun Apr 10 20:24:21 EDT 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secquestion
     *
     * @mbggenerated Sun Apr 10 20:24:21 EDT 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secquestion
     *
     * @mbggenerated Sun Apr 10 20:24:21 EDT 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secquestion
     *
     * @mbggenerated Sun Apr 10 20:24:21 EDT 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secquestion
     *
     * @mbggenerated Sun Apr 10 20:24:21 EDT 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secquestion
     *
     * @mbggenerated Sun Apr 10 20:24:21 EDT 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secquestion
     *
     * @mbggenerated Sun Apr 10 20:24:21 EDT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table secquestion
     *
     * @mbggenerated Sun Apr 10 20:24:21 EDT 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSecQuestionIdIsNull() {
            addCriterion("sec_question_id is null");
            return (Criteria) this;
        }

        public Criteria andSecQuestionIdIsNotNull() {
            addCriterion("sec_question_id is not null");
            return (Criteria) this;
        }

        public Criteria andSecQuestionIdEqualTo(Integer value) {
            addCriterion("sec_question_id =", value, "secQuestionId");
            return (Criteria) this;
        }

        public Criteria andSecQuestionIdNotEqualTo(Integer value) {
            addCriterion("sec_question_id <>", value, "secQuestionId");
            return (Criteria) this;
        }

        public Criteria andSecQuestionIdGreaterThan(Integer value) {
            addCriterion("sec_question_id >", value, "secQuestionId");
            return (Criteria) this;
        }

        public Criteria andSecQuestionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sec_question_id >=", value, "secQuestionId");
            return (Criteria) this;
        }

        public Criteria andSecQuestionIdLessThan(Integer value) {
            addCriterion("sec_question_id <", value, "secQuestionId");
            return (Criteria) this;
        }

        public Criteria andSecQuestionIdLessThanOrEqualTo(Integer value) {
            addCriterion("sec_question_id <=", value, "secQuestionId");
            return (Criteria) this;
        }

        public Criteria andSecQuestionIdIn(List<Integer> values) {
            addCriterion("sec_question_id in", values, "secQuestionId");
            return (Criteria) this;
        }

        public Criteria andSecQuestionIdNotIn(List<Integer> values) {
            addCriterion("sec_question_id not in", values, "secQuestionId");
            return (Criteria) this;
        }

        public Criteria andSecQuestionIdBetween(Integer value1, Integer value2) {
            addCriterion("sec_question_id between", value1, value2, "secQuestionId");
            return (Criteria) this;
        }

        public Criteria andSecQuestionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sec_question_id not between", value1, value2, "secQuestionId");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table secquestion
     *
     * @mbggenerated do_not_delete_during_merge Sun Apr 10 20:24:21 EDT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table secquestion
     *
     * @mbggenerated Sun Apr 10 20:24:21 EDT 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}