package edu.fiu.hmts.domain;

public class SelProductKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selproduct.product_id
     *
     * @mbggenerated Thu Mar 03 13:04:34 EST 2016
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selproduct.user_id
     *
     * @mbggenerated Thu Mar 03 13:04:34 EST 2016
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selproduct.product_id
     *
     * @return the value of selproduct.product_id
     *
     * @mbggenerated Thu Mar 03 13:04:34 EST 2016
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selproduct.product_id
     *
     * @param productId the value for selproduct.product_id
     *
     * @mbggenerated Thu Mar 03 13:04:34 EST 2016
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selproduct.user_id
     *
     * @return the value of selproduct.user_id
     *
     * @mbggenerated Thu Mar 03 13:04:34 EST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selproduct.user_id
     *
     * @param userId the value for selproduct.user_id
     *
     * @mbggenerated Thu Mar 03 13:04:34 EST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}