package edu.fiu.hmts.domain;

public class SelProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selproduct.product_id
     *
     * @mbggenerated Sun Apr 10 20:24:21 EDT 2016
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selproduct.user_id
     *
     * @mbggenerated Sun Apr 10 20:24:21 EDT 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selproduct.quantity
     *
     * @mbggenerated Sun Apr 10 20:24:21 EDT 2016
     */
    private Integer quantity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selproduct.product_id
     *
     * @return the value of selproduct.product_id
     *
     * @mbggenerated Sun Apr 10 20:24:21 EDT 2016
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selproduct.product_id
     *
     * @param productId the value for selproduct.product_id
     *
     * @mbggenerated Sun Apr 10 20:24:21 EDT 2016
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selproduct.user_id
     *
     * @return the value of selproduct.user_id
     *
     * @mbggenerated Sun Apr 10 20:24:21 EDT 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selproduct.user_id
     *
     * @param userId the value for selproduct.user_id
     *
     * @mbggenerated Sun Apr 10 20:24:21 EDT 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selproduct.quantity
     *
     * @return the value of selproduct.quantity
     *
     * @mbggenerated Sun Apr 10 20:24:21 EDT 2016
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selproduct.quantity
     *
     * @param quantity the value for selproduct.quantity
     *
     * @mbggenerated Sun Apr 10 20:24:21 EDT 2016
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
}