package edu.fiu.hmts.domain;

/**
 * The Class SelProductKey.
 */
public class SelProductKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selproduct.product_id
     *
     * 
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selproduct.user_id
     *
     * 
     */
    private Integer userId;

    /**
	 * Gets the product id.
	 *
	 * @return the product id
	 */
    public Integer getProductId() {
        return productId;
    }

    /**
	 * Sets the product id.
	 *
	 * @param productId
	 *            the new product id
	 */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
	 * Gets the user id.
	 *
	 * @return the user id
	 */
    public Integer getUserId() {
        return userId;
    }

    /**
	 * Sets the user id.
	 *
	 * @param userId
	 *            the new user id
	 */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}