package edu.fiu.hmts.domain;

/**
 * The Class User.
 */
public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * 
     */
    private Integer userId = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * 
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * 
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.first_name
     *
     * 
     */
    private String firstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.last_name
     *
     * 
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * 
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.role
     *
     * 
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sec_question_id
     *
     * 
     */
    private Integer secQuestionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sec_answer
     *
     * 
     */
    private String secAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.tag
     *
     * 
     */
    private String tag;

    /**
	 * Gets the user id.
	 *
	 * @return the user id
	 */
    public Integer getUserId() {
        return userId;
    }

    /**
	 * Sets the user id.
	 *
	 * @param userId
	 *            the new user id
	 */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
	 * Gets the username.
	 *
	 * @return the username
	 */
    public String getUsername() {
        return username;
    }

    /**
	 * Sets the username.
	 *
	 * @param username
	 *            the new username
	 */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
	 * Gets the password.
	 *
	 * @return the password
	 */
    public String getPassword() {
        return password;
    }

    /**
	 * Sets the password.
	 *
	 * @param password
	 *            the new password
	 */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
	 * Gets the first name.
	 *
	 * @return the first name
	 */
    public String getFirstName() {
        return firstName;
    }

    /**
	 * Sets the first name.
	 *
	 * @param firstName
	 *            the new first name
	 */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
	 * Gets the last name.
	 *
	 * @return the last name
	 */
    public String getLastName() {
        return lastName;
    }

    /**
	 * Sets the last name.
	 *
	 * @param lastName
	 *            the new last name
	 */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
	 * Gets the phone.
	 *
	 * @return the phone
	 */
    public String getPhone() {
        return phone;
    }

    /**
	 * Sets the phone.
	 *
	 * @param phone
	 *            the new phone
	 */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
	 * Gets the role.
	 *
	 * @return the role
	 */
    public String getRole() {
        return role;
    }

    /**
	 * Sets the role.
	 *
	 * @param role
	 *            the new role
	 */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
	 * Gets the sec question id.
	 *
	 * @return the sec question id
	 */
    public Integer getSecQuestionId() {
        return secQuestionId;
    }

    /**
	 * Sets the sec question id.
	 *
	 * @param secQuestionId
	 *            the new sec question id
	 */
    public void setSecQuestionId(Integer secQuestionId) {
        this.secQuestionId = secQuestionId;
    }

    /**
	 * Gets the sec answer.
	 *
	 * @return the sec answer
	 */
    public String getSecAnswer() {
        return secAnswer;
    }

    /**
	 * Sets the sec answer.
	 *
	 * @param secAnswer
	 *            the new sec answer
	 */
    public void setSecAnswer(String secAnswer) {
        this.secAnswer = secAnswer == null ? null : secAnswer.trim();
    }

    /**
	 * Gets the tag.
	 *
	 * @return the tag
	 */
    public String getTag() {
        return tag;
    }

    /**
	 * Sets the tag.
	 *
	 * @param tag
	 *            the new tag
	 */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }
}