package edu.fiu.hmts.dao.hmts_repos;

import edu.fiu.hmts.domain.hmts_repos.Card;
import edu.fiu.hmts.domain.hmts_repos.CardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card
     *
     * @mbggenerated Sun Apr 10 22:11:08 EDT 2016
     */
    int countByExample(CardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card
     *
     * @mbggenerated Sun Apr 10 22:11:08 EDT 2016
     */
    int deleteByExample(CardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card
     *
     * @mbggenerated Sun Apr 10 22:11:08 EDT 2016
     */
    int deleteByPrimaryKey(Long cardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card
     *
     * @mbggenerated Sun Apr 10 22:11:08 EDT 2016
     */
    int insert(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card
     *
     * @mbggenerated Sun Apr 10 22:11:08 EDT 2016
     */
    int insertSelective(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card
     *
     * @mbggenerated Sun Apr 10 22:11:08 EDT 2016
     */
    List<Card> selectByExample(CardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card
     *
     * @mbggenerated Sun Apr 10 22:11:08 EDT 2016
     */
    Card selectByPrimaryKey(Long cardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card
     *
     * @mbggenerated Sun Apr 10 22:11:08 EDT 2016
     */
    int updateByExampleSelective(@Param("record") Card record, @Param("example") CardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card
     *
     * @mbggenerated Sun Apr 10 22:11:08 EDT 2016
     */
    int updateByExample(@Param("record") Card record, @Param("example") CardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card
     *
     * @mbggenerated Sun Apr 10 22:11:08 EDT 2016
     */
    int updateByPrimaryKeySelective(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card
     *
     * @mbggenerated Sun Apr 10 22:11:08 EDT 2016
     */
    int updateByPrimaryKey(Card record);
}