package edu.fiu.hmts.dao.hmts_repos;

import edu.fiu.hmts.domain.hmts_repos.SelProduct;
import edu.fiu.hmts.domain.hmts_repos.SelProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SelProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selproduct
     *
     * @mbggenerated Sun Apr 10 22:11:08 EDT 2016
     */
    int countByExample(SelProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selproduct
     *
     * @mbggenerated Sun Apr 10 22:11:08 EDT 2016
     */
    int deleteByExample(SelProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selproduct
     *
     * @mbggenerated Sun Apr 10 22:11:08 EDT 2016
     */
    int insert(SelProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selproduct
     *
     * @mbggenerated Sun Apr 10 22:11:08 EDT 2016
     */
    int insertSelective(SelProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selproduct
     *
     * @mbggenerated Sun Apr 10 22:11:08 EDT 2016
     */
    List<SelProduct> selectByExample(SelProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selproduct
     *
     * @mbggenerated Sun Apr 10 22:11:08 EDT 2016
     */
    int updateByExampleSelective(@Param("record") SelProduct record, @Param("example") SelProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selproduct
     *
     * @mbggenerated Sun Apr 10 22:11:08 EDT 2016
     */
    int updateByExample(@Param("record") SelProduct record, @Param("example") SelProductExample example);
}