package edu.fiu.hmts.dao.mybatis.dao;

import edu.fiu.hmts.domain.SecQuestion;
import edu.fiu.hmts.domain.SecQuestionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secquestion
     *
     * @mbggenerated Sun Feb 28 12:46:23 EST 2016
     */
    int countByExample(SecQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secquestion
     *
     * @mbggenerated Sun Feb 28 12:46:23 EST 2016
     */
    int deleteByExample(SecQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secquestion
     *
     * @mbggenerated Sun Feb 28 12:46:23 EST 2016
     */
    int deleteByPrimaryKey(Integer secQuestionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secquestion
     *
     * @mbggenerated Sun Feb 28 12:46:23 EST 2016
     */
    int insert(SecQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secquestion
     *
     * @mbggenerated Sun Feb 28 12:46:23 EST 2016
     */
    int insertSelective(SecQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secquestion
     *
     * @mbggenerated Sun Feb 28 12:46:23 EST 2016
     */
    List<SecQuestion> selectByExample(SecQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secquestion
     *
     * @mbggenerated Sun Feb 28 12:46:23 EST 2016
     */
    SecQuestion selectByPrimaryKey(Integer secQuestionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secquestion
     *
     * @mbggenerated Sun Feb 28 12:46:23 EST 2016
     */
    int updateByExampleSelective(@Param("record") SecQuestion record, @Param("example") SecQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secquestion
     *
     * @mbggenerated Sun Feb 28 12:46:23 EST 2016
     */
    int updateByExample(@Param("record") SecQuestion record, @Param("example") SecQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secquestion
     *
     * @mbggenerated Sun Feb 28 12:46:23 EST 2016
     */
    int updateByPrimaryKeySelective(SecQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secquestion
     *
     * @mbggenerated Sun Feb 28 12:46:23 EST 2016
     */
    int updateByPrimaryKey(SecQuestion record);
}