package edu.fiu.hmts.domain;

public class CardKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.card_id
     *
     * @mbggenerated Sun Feb 28 17:00:29 EST 2016
     */
    private Integer cardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.payment_id
     *
     * @mbggenerated Sun Feb 28 17:00:29 EST 2016
     */
    private Integer paymentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.card_id
     *
     * @return the value of card.card_id
     *
     * @mbggenerated Sun Feb 28 17:00:29 EST 2016
     */
    public Integer getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.card_id
     *
     * @param cardId the value for card.card_id
     *
     * @mbggenerated Sun Feb 28 17:00:29 EST 2016
     */
    public void setCardId(Integer cardId) {
        this.cardId = cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.payment_id
     *
     * @return the value of card.payment_id
     *
     * @mbggenerated Sun Feb 28 17:00:29 EST 2016
     */
    public Integer getPaymentId() {
        return paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.payment_id
     *
     * @param paymentId the value for card.payment_id
     *
     * @mbggenerated Sun Feb 28 17:00:29 EST 2016
     */
    public void setPaymentId(Integer paymentId) {
        this.paymentId = paymentId;
    }
}