package edu.fiu.hmts.domain;

public class SecQuestion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secquestion.sec_question_id
     *
     * @mbggenerated Sun Feb 28 12:46:23 EST 2016
     */
    private Integer secQuestionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secquestion.content
     *
     * @mbggenerated Sun Feb 28 12:46:23 EST 2016
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secquestion.sec_question_id
     *
     * @return the value of secquestion.sec_question_id
     *
     * @mbggenerated Sun Feb 28 12:46:23 EST 2016
     */
    public Integer getSecQuestionId() {
        return secQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secquestion.sec_question_id
     *
     * @param secQuestionId the value for secquestion.sec_question_id
     *
     * @mbggenerated Sun Feb 28 12:46:23 EST 2016
     */
    public void setSecQuestionId(Integer secQuestionId) {
        this.secQuestionId = secQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secquestion.content
     *
     * @return the value of secquestion.content
     *
     * @mbggenerated Sun Feb 28 12:46:23 EST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secquestion.content
     *
     * @param content the value for secquestion.content
     *
     * @mbggenerated Sun Feb 28 12:46:23 EST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}